"$schema" = "https://starship.rs/config-schema.json"

add_newline = false
command_timeout = 1000
scan_timeout = 30

format = """
$directory\
$git_branch\
$nodejs\
$bun\
$rust\
$golang\
$php\
\n$character"""

[directory]
# style = "fg:#ffffff bg:#43766a"
style = "fg:#D2D6DC"
format = "[$path ]($style)"
truncate_to_repo = false
#truncation_length = 3
#truncation_symbol = "…/"

[git_branch]
symbol = ""
# style = "bg:#2b4841"
format = '[[ $symbol $branch ](fg:#ABB2BF)]($style)'

[git_status]
style = "bg:#2b4841"
format = '[[($all_status$ahead_behind )](fg:#8ac6b8 bg:#2b4841)]($style)'

[cmd_duration]
disabled = true
min_time = 1000
format = " took [$duration]($style)"
style = "bold yellow"

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

[package]
disabled = true
